image: ubuntu:latest
tasks:
    init: sudo apt update -y
    command: sudo pip3 install molecule[docker] ansible
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: true
    addBadge: true
