image: ubuntu:latest
tasks:
  - init: |
      sudo apt update -y
      sudo pip3 install molecule[docker] ansible
    command: |
      mkdir ~/tmp
      echo ok
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: true
    addBadge: true
